### ISSUE TITLE
GPLv3

### ISSUE THREAD

**Issue by brucehoult** [lizhirui/K210-Linux0.11#1]
Hi, this is really great! I have a Maixduino and would be keen to try this out soon!

However you don't make clear exactly what this is. Is it Linus's December 1991 Linux code ported to RISC-V and Priv 1.9.1? Or is the version number coincidental?

You should note that the Linux license is *exactly* GPLv2, deliberately without the common "or any later version" option. Linus doesn't like GPLv3.

**Comment by lizhirui** [comment]
Thanks for your issue.
This is the version ported to RISC-V and Priv- 1.9.1 of Linus's December 1991 Linux code.And this is not final version because the final version is stored in school and  I can't go back to school recently because of novel coronavirus.
I can't find the shell source of Linux 0.11,so I wrote a simple version of shell which contains simple "ls" command only.
And I'm sorry that I did't know something about Linux license before.
I have changed the License to GPLv2 just now.

**Comment by brucehoult** [comment]
Thank you for your quick response!

**Comment by brucehoult** [comment]
By the way, we are discussing this work at https://www.reddit.com/r/RISCV/comments/fguddz/linux011_with_mmu_for_k210_riscv/

**Comment by lizhirui** [comment]
OK.I will go to see it.
